const ADD_ERROR_SUCCESS = 'ADD_ERROR_SUCCESS';
const REMOVE_ERROR_SUCCESS = 'REMOVE_ERROR_SUCCESS';
const FORM_IS_SUBMITTED = 'FORM_IS_SUBMITTED';
const ADD_SHOULD_SUBMIT = 'ADD_SHOULD_SUBMIT';
const CHANGE_SHOULD_SUBMIT = 'CHANGE_SHOULD_SUBMIT';
const CLEAR_SHOULD_SUBMIT = 'CLEAR_SHOULD_SUBMIT';
const MODULE_IS_SUBMITTED = 'MODULE_IS_SUBMITTED';

export {
    ADD_ERROR_SUCCESS,
    REMOVE_ERROR_SUCCESS,
    FORM_IS_SUBMITTED,
    ADD_SHOULD_SUBMIT,
    CHANGE_SHOULD_SUBMIT,
    CLEAR_SHOULD_SUBMIT,
    MODULE_IS_SUBMITTED
}